VENCEDOR_CHOICES = {
    'CASA': 'CASA',
    'FORA': 'FORA',
    'EMPATE': 'EMPATE',
}
STATUS_BOLAO = {
    'ATIVO': 'ATIVO',
    'PALPITES PAUSADOS': 'PALPITES PAUSADOS',
    'JOGO INICIADO': 'JOGO INICIADO',
    'FINALIZADO': 'FINALIZADO',
    'CANCELADO': 'CANCELADO'
}

STATUS_JOGO_FINALIZADO_API = 'FT-AET-AET'
