VENCEDOR_CHOICES = {
    'CASA': 'CASA',
    'FORA': 'FORA',
    'EMPATE': 'EMPATE',
}
STATUS_BOLAO = {
    'ATIVO': 'AT',
    'PALPITES PAUSADOS': 'PP',
    'JOGO INICIADO': 'JI',
    'FINALIZADO': 'FI'
}