version: '3.8'

services:
  redis:
    image: redis:alpine

  django:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    env_file: ./.env
    depends_on:
      - redis

  celery:
    build:
      context: .
    command: celery -A api_bolao worker -l info
    volumes:
      - .:/code
    env_file: ./.env
    depends_on:
      - redis

  flower:
    build:
      context: .
    command: >
      sh -c "celery -A api_bolao flower --port=5555 --broker=$CELERY_BROKER"
    ports:
      - 5555:5555
    env_file: ./.env
    depends_on:
      - redis
