version: '3.8'

services:

  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          memory: 64M
    volumes:
      - redis_data:/etc/redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api_bolao:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file: ./.env
    depends_on:
      - redis
      - db

  celery_worker:
    build:
      context: .
    command: celery -A api_bolao worker -l info
    volumes:
      - .:/code
    env_file: ./.env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
    command: celery -A api_bolao beat -l info
    volumes:
      - .:/code
    env_file: ./.env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
    command: >
      sh -c "celery -A api_bolao flower --basic_auth=$FLOWER_USER:$FLOWER_PASSWORD"
    ports:
      - 5555:5555
    env_file: ./.env
    depends_on:
      - redis
      - celery_worker
      - celery_beat

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api_bolao

volumes:
  postgres_data:
  redis_data:
