@startuml packages
set namespaceSeparator none
package "bolao" as bolao #aliceblue {
}
package "bolao.forms" as bolao.forms #aliceblue {
}
package "bolao.models" as bolao.models #aliceblue {
}
package "core" as core #antiquewhite {
}
package "core.custom_exception" as core.custom_exception #antiquewhite {
}
package "core.models" as core.models #antiquewhite {
}
package "core.network" as core.network #aquamarine {
}
package "core.network.football" as core.network.football #aquamarine {
}
package "core.utils" as core.utils #antiquewhite {
}
package "usuario" as usuario #burlywood {
}
package "usuario.api" as usuario.api #cadetblue {
}
package "usuario.api.serializers" as usuario.api.serializers #cadetblue {
}
package "usuario.api.viewsets" as usuario.api.viewsets #cadetblue {
}
package "usuario.managers" as usuario.managers #burlywood {
}
package "usuario.models" as usuario.models #burlywood {
}
package "usuario.urls" as usuario.urls #burlywood {
}
bolao.forms --> bolao.models
bolao.models --> core.models
bolao.models --> core.utils
bolao.models --> usuario.models
core.network.football --> bolao
core.network.football --> bolao.models
usuario.api.serializers --> core.custom_exception
usuario.api.serializers --> usuario.models
usuario.api.viewsets --> core.custom_exception
usuario.api.viewsets --> usuario.api.serializers
usuario.api.viewsets --> usuario.models
usuario.models --> core.custom_exception
usuario.models --> core.models
usuario.models --> core.utils
usuario.models --> usuario.managers
usuario.urls --> usuario.api.viewsets
@enduml
