# Generated by Django 4.1.7 on 2023-03-22 02:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0009_rename_created_carteira_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTransacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('SAQUE', 'Saque'), ('COMPRA', 'Compra'), ('GANHO', 'Ganho')], max_length=10, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('externo', models.BooleanField(default=False, verbose_name='Transação externa')),
                ('pix', models.CharField(blank=True, max_length=50, null=True, verbose_name='PIX')),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_transacao', to='usuario.carteira')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
