# Generated by Django 4.0 on 2023-10-19 00:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsaasInformations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('billing_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cobrança ID')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('net_value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor efetivo')),
                ('invoice_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='URL da cobrança')),
                ('billet_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='URL do boleto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='historicotransacao',
            name='status',
            field=models.CharField(choices=[('VALID', 'Válido'), ('REMOVED', 'Removido'), ('PENDING', 'Pendente')], default='VALID', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='historicotransacao',
            name='asaas_infos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_transacao', to='core.asaasinformations'),
        ),
    ]
