# Generated by Django 4.0 on 2023-10-23 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_remove_carteira_pix_contaexternausuario'),
        ('core', '0002_asaasinformations_historicotransacao_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicotransacao',
            options={'verbose_name': 'Transação', 'verbose_name_plural': 'Histórico transações'},
        ),
        migrations.RemoveField(
            model_name='asaasinformations',
            name='billing_id',
        ),
        migrations.RemoveField(
            model_name='historicotransacao',
            name='pix',
        ),
        migrations.AddField(
            model_name='asaasinformations',
            name='asaas_id',
            field=models.CharField(default='none', max_length=50, verbose_name='ID Asaas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asaasinformations',
            name='op_type',
            field=models.CharField(default='payment', max_length=50, verbose_name='Tipo da operação'),
        ),
        migrations.AddField(
            model_name='historicotransacao',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_transacao', to='usuario.contaexternausuario'),
        ),
        migrations.AlterField(
            model_name='historicotransacao',
            name='status',
            field=models.CharField(choices=[('REMOVED', 'REMOVED'), ('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED')], default='CONFIRMED', max_length=10, verbose_name='Status'),
        ),
    ]
