TIPO_CHOICES = {
    'DEPOSITO': 'Depósito',
    'SAQUE': 'Saque',
    'COMPRA': 'Compra',
    'GANHO': 'Ganho'
}

STATUS_HISTORICO = {
    'REMOVED': 'REMOVED',
    'PENDING': 'PENDING',
    'CONFIRMED': 'CONFIRMED',
    'FAILED': 'FAILED'
}

TIPO_CONTA = {
    "CONTA_CORRENTE": "CONTA_CORRENTE",
    "CONTA_POUPANCA": "CONTA_POUPANCA"
}