# Generated by Django 4.1.7 on 2023-03-10 21:30

from django.db import migrations, models
import django.db.models.deletion
import usuario.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Saldo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('estado', models.CharField(max_length=25, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=75, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=25, verbose_name='Bairro')),
                ('rua', models.CharField(blank=True, max_length=75, null=True, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=75, null=True, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='PermissoesNotificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('sms', models.BooleanField(default=True, verbose_name='SMS')),
                ('email', models.BooleanField(default=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Pemissão para notificação',
                'verbose_name_plural': 'Pemissões para notificações',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('cpf', models.CharField(editable=False, max_length=14, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('carteira', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.carteira')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuario.endereco')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('permissoes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuario.PermissoesNotificacao')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', usuario.managers.UserManager()),
            ],
        ),
    ]
