# Generated by Django 4.1.7 on 2023-03-13 02:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_carteira_updated_endereco_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Saldo'),
        ),
    ]
