# Generated by Django 4.1.7 on 2023-03-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_usuario_cpf_remove_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default='06515321325', editable=False, max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default='89994619853', max_length=11, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
