# Generated by Django 4.1.7 on 2023-03-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_usuario_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carteira',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='carteira',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='permissoesnotificacao',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='permissoesnotificacao',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
