# Generated by Django 4.1.7 on 2023-03-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_rename_created_carteira_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Carteira bloqueada'),
        ),
        migrations.AddField(
            model_name='carteira',
            name='pix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
