# Generated by Django 4.1.7 on 2023-03-24 23:40

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_carteira_bloqueado_carteira_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carteira',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.carteira'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[core.utils.cpf_valido], verbose_name='CPF'),
        ),
    ]
