# Generated by Django 4.1.7 on 2023-03-25 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_usuario_carteira_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carteira',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='usuario.carteira'),
        ),
    ]
