# Generated by Django 4.1.7 on 2023-03-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_permissoesnotificacao_email_verificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigosdevalidacao',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Confirmado'),
        ),
    ]
