# Generated by Django 4.1.7 on 2023-03-28 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_codigosdevalidacao_confirmado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='permissoes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='usuario.permissoesnotificacao'),
        ),
    ]
