# Generated by Django 4.0 on 2023-10-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0015_alter_usuario_permissoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='asaas_customer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Asaas CustomerID'),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='pix',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pix'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
