# Generated by Django 4.0 on 2023-10-23 23:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_carteira_asaas_customer_alter_carteira_pix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteira',
            name='pix',
        ),
        migrations.CreateModel(
            name='ContaExternaUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code_banco', models.CharField(max_length=5, verbose_name='Código bancario')),
                ('agencia', models.CharField(max_length=5, verbose_name='Agencia')),
                ('tipo_conta', models.CharField(choices=[('CONTA_CORRENTE', 'CONTA_CORRENTE'), ('CONTA_POUPANCA', 'CONTA_POUPANCA')], max_length=20, verbose_name='Tipo de conta')),
                ('num_conta', models.CharField(max_length=15, verbose_name='Conta')),
                ('digito', models.CharField(max_length=5, verbose_name='Digito')),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_externa', to='usuario.carteira', verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Conta externa',
                'verbose_name_plural': 'Contas externa',
            },
        ),
    ]
