# Generated by Django 4.1.7 on 2023-03-13 01:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=75, verbose_name='Nome')),
                ('pais', models.CharField(max_length=75, verbose_name='País')),
                ('tipo', models.CharField(blank=True, max_length=75, null=True, verbose_name='Tipo')),
                ('id_externo', models.CharField(blank=True, max_length=25, null=True, verbose_name='ID externo')),
                ('logo', models.URLField(blank=True, null=True, verbose_name='Logo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('temporada_atual', models.CharField(max_length=75, verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_externo', models.CharField(max_length=50, verbose_name='ID externo')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('logo', models.URLField(verbose_name='Logo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_externo', models.CharField(max_length=50, verbose_name='ID externo')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('placar_casa', models.IntegerField(blank=True, null=True, verbose_name='Placar casa')),
                ('placar_fora', models.IntegerField(blank=True, null=True, verbose_name='Placar Fora')),
                ('vencedor', models.CharField(blank=True, choices=[('CASA', 'CASA'), ('FORA', 'FORA'), ('EMPATE', 'EMPATE')], max_length=6, null=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogos', to='bolao.campeonato', verbose_name='Campeonato')),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_casa', to='bolao.time', verbose_name='Time casa')),
                ('time_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_fora', to='bolao.time', verbose_name='Time fora')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
    ]
