# Generated by Django 4.1.7 on 2023-03-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campeonato',
            options={'ordering': ['ativo', 'nome'], 'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='id_externo',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='ID externo'),
        ),
    ]
