# Generated by Django 4.1.7 on 2023-03-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0003_alter_jogo_id_externo_alter_time_id_externo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogo',
            options={'ordering': ['-data', 'status'], 'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['nome'], 'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
    ]
