# Generated by Django 4.1.7 on 2023-03-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0004_alter_jogo_options_alter_time_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campeonato',
            options={'ordering': ['-ativo', 'nome'], 'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
    ]
