# Generated by Django 4.1.7 on 2023-03-15 21:19

from core.utils import gerar_codigo, get_taxa_banca
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bolao', '0005_alter_campeonato_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor_palpite', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(Decimal('1000')), django.core.validators.MinValueValidator(Decimal('2'))], verbose_name='Valor palpite')),
                ('codigo', models.CharField(default=gerar_codigo, max_length=25, verbose_name='Código')),
                ('estorno', models.BooleanField(default=False, verbose_name='Estorno')),
                ('taxa_banca', models.FloatField(default=get_taxa_banca, verbose_name='Taxa banca')),
                ('taxa_criador', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(15.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Taxa banca')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boloes', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('jogos', models.ManyToManyField(related_name='boloes', to='bolao.jogo', verbose_name='Jogos')),
            ],
            options={
                'verbose_name': 'Bolão',
                'verbose_name_plural': 'Bolões',
            },
        ),
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('bolao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palpites', to='bolao.bolao', verbose_name='Bolão')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palpites', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Palpite',
                'verbose_name_plural': 'Palpites',
            },
        ),
        migrations.CreateModel(
            name='PalpitePlacar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar_casa', models.IntegerField(verbose_name='Placar casa')),
                ('placar_fora', models.IntegerField(verbose_name='Placar Fora')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palpites_placar', to='bolao.jogo', verbose_name='Jogo')),
                ('palpite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placares', to='bolao.palpite', verbose_name='Palpite')),
            ],
            options={
                'verbose_name': 'Placar',
                'verbose_name_plural': 'Placares',
            },
        ),
    ]
