# Generated by Django 4.1.7 on 2023-03-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0006_bolao_palpite_palpiteplacar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bolao',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bolao',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='campeonato',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='campeonato',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='jogo',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='jogo',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='palpite',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='palpite',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
