# Generated by Django 4.1.7 on 2023-03-17 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0008_bolao_vencedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolao',
            name='taxa_criador',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(15.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Taxa criador'),
        ),
    ]
