# Generated by Django 4.1.7 on 2023-03-31 22:49

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bolao', '0010_remove_bolao_vencedor_bolao_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Bilhete',
                'verbose_name_plural': 'Palpites',
            },
        ),
        migrations.RemoveField(
            model_name='palpiteplacar',
            name='palpite',
        ),
        migrations.AlterField(
            model_name='bolao',
            name='valor_palpite',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(Decimal('1000')), django.core.validators.MinValueValidator(Decimal('2'))], verbose_name='Valor bilhete'),
        ),
        migrations.DeleteModel(
            name='Palpite',
        ),
        migrations.AddField(
            model_name='bilhete',
            name='bolao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bilhetes', to='bolao.bolao', verbose_name='Bolão'),
        ),
        migrations.AddField(
            model_name='bilhete',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bilhetes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='palpiteplacar',
            name='bilhete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placares', to='bolao.bilhete', verbose_name='Bilhete'),
        ),
    ]
