# Generated by Django 4.1.7 on 2023-03-31 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0011_bilhete_remove_palpiteplacar_palpite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar_casa', models.IntegerField(verbose_name='Placar casa')),
                ('placar_fora', models.IntegerField(verbose_name='Placar Fora')),
                ('bilhete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palpites', to='bolao.bilhete', verbose_name='Bilhete')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palpites', to='bolao.jogo', verbose_name='Jogo')),
            ],
            options={
                'verbose_name': 'Palpite',
                'verbose_name_plural': 'Palpites',
            },
        ),
        migrations.DeleteModel(
            name='PalpitePlacar',
        ),
    ]
