# Generated by Django 4.1.7 on 2023-04-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0012_palpite_delete_palpiteplacar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bilhete',
            options={'verbose_name': 'Bilhete', 'verbose_name_plural': 'Bilhetes'},
        ),
    ]
