# Generated by Django 4.0 on 2023-10-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0014_bolao_bilhetes_minimos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolao',
            name='jogos',
            field=models.ManyToManyField(related_name='boloes', to='bolao.Jogo', verbose_name='Jogos'),
        ),
    ]
